services:
  - type: web
    name: bhai-jaan-academy-api
    env: python
    buildCommand: cd backend && uv sync
    startCommand: cd backend && uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SENDGRID_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NETLIFY_ACCESS_TOKEN
        sync: false
      - key: NETLIFY_SITE_ID
        sync: false 