name: Daily Report Scheduler

on:
  schedule:
    - cron: '0 18 * * *'  # Every day at 16:00 Amsterdam time (14:00 UTC, correct for summer)
  workflow_dispatch:

jobs:
  trigger-backend-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend scheduler endpoint
        run: |
          curl -X POST "https://bhai-jaan-academy.onrender.com/run-scheduler" 
