name: Daily Report Scheduler

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8:00 AM UTC
  workflow_dispatch:

jobs:
  trigger-backend-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend scheduler endpoint
        env:
          SCHEDULER_TOKEN: ${{ secrets.SCHEDULER_TOKEN }}
        run: |
          curl -X POST "https://bhai-jaan-academy.onrender.com/run-scheduler" \
            -H "X-Scheduler-Token: $SCHEDULER_TOKEN" 